volumes:
  mssql1-data:
    driver: local
  mssql2-data:
    driver: local
  mongodb-data:
    driver: local
  redis-cache:
    driver: local
  redis-database:
    driver: local

services:
  
  basket_api:
    container_name: basket_api.container
    image: basket_api
    build:
      context: .
      dockerfile: Basket_API/Dockerfile
    depends_on:
      - redis-cache_server
      - sql_server2
    ports:
      - 8080:8080
    networks:
      - basket_backend.networks
  
  identity_api:
    container_name: identity_api.container
    image: identity_api
    build:
      context: .
      dockerfile: Identity_API/Dockerfile
    depends_on:
      - sql_server1
    environment:
      - DB_HOST=sql_server1
      - DB_PASSWORD=Nam09189921
    ports:
      - 8081:8080
    networks:
      - identity_backend.networks
  
  product_api:
    container_name: product_api.container
    image: product_api
    build:
      context: .
      dockerfile: Product_API/Dockerfile
    depends_on:
      - redis-database_server 
      - azurite
    ports:
      - 8082:8080
    networks:
      - product_backend.networks 
  
  sql_server1:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server1.container
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Nam09189921
      MSSQL_PID: Express
    ports:
      - 8070:1433
    volumes:
      - mssql1-data:/var/opt/mssql
    networks:
      - identity_backend.networks
  
  sql_server2:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server2.container
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Nam09189921
      MSSQL_PID: Express
    ports:
      - 8071:1433
    volumes:
      - mssql2-data:/var/opt/mssql
    networks:
      - basket_backend.networks
  
  redis-cache_server:
    image: redis
    container_name: redis-cache_server.container
    ports:
      - 8074:6379
    volumes:
      - redis-cache:/data
    networks:
      - basket_backend.networks
  
  redis-database_server:
    image: redis
    container_name: redis-database_server.container
    ports:
      - 8075:6379
    volumes:
      - redis-database:/data
    networks:
      - product_backend.networks
 
  azurite:
    container_name: azurite
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - 8073:10000
    restart: always
    volumes:
      - /home/khauvannam/Azurite/blob-data:/data
    command:
      "azurite-blob --blobHost 0.0.0.0 -l /data"

networks:
  identity_backend.networks:
  basket_backend.networks:
  product_backend.networks:
  message_broker:
  frontend:
  backend:
