volumes:
  mssql-data:
    driver: local
  mongodb-data:
    driver: local

services:
  
  identity_api:
    container_name: identity_api.container
    image: identity_api
    build:
      context: .
      dockerfile: Identity_API/Dockerfile
    depends_on:
      - sql_server
    environment:
      - DB_HOST=sql_server
      - DB_PASSWORD=Nam09189921
    ports:
      - 8081:8080
    networks:
      - sql_server.networks
  
  
  product_api:
    container_name: product_api.container
    image: product_api
    build:
      context: .
      dockerfile: Product_API/Dockerfile
    depends_on:
      - mongodb_server
      - azurite
    ports:
      - 8083:8080
  
  sql_server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server.container
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Nam09189921
      MSSQL_PID: Express
    ports:
      - 8084:1433
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - sql_server.networks
  
  mongodb_server:
    image: mongo
    container_name: mongodb_server.container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27018:27017
    volumes:
      - mongodb-data:/data/db
  
  azurite:
    container_name: azurite
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - 8880:10000
    restart: always
    volumes:
      - D:/Azurite/blob-data:/data

networks:
  sql_server.networks:
