volumes:
  mssql1-data:
    driver: local
  mssql2-data:
    driver: local
  mongodb-data:
    driver: local
  redis-data:
    driver: local

services:
  basket_api:
    container_name: basket_api.container
    image: basket_api
    build:
      context: .
      dockerfile: Basket_API/Dockerfile
    depends_on:
      - redis-cache_server
      - sql_server2
    ports:
      - 8080:8080
    networks:
      - sql_server_basket.networks
  
  identity_api:
    container_name: identity_api.container
    image: identity_api
    build:
      context: .
      dockerfile: Identity_API/Dockerfile
    depends_on:
      - sql_server1
    environment:
      - DB_HOST=sql_server1
      - DB_PASSWORD=Nam09189921
    ports:
      - 8081:8080
    networks:
      - sql_server_identity.networks
  
  product_api:
    container_name: product_api.container
    image: product_api
    build:
      context: .
      dockerfile: Product_API/Dockerfile
    depends_on:
      - mongodb_server
      - azurite
    ports:
      - 8082:8080
  
  sql_server1:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server1.container
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Nam09189921
      MSSQL_PID: Express
    ports:
      - 8070:1433
    volumes:
      - mssql1-data:/var/opt/mssql
    networks:
      - sql_server_identity.networks
  
  sql_server2:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server2.container
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Nam09189921
      MSSQL_PID: Express
    ports:
      - 8071:1433
    volumes:
      - mssql2-data:/var/opt/mssql
    networks:
      - sql_server_basket.networks
  
  redis-cache_server:
    image: redis
    container_name: redis-cache_server.container
    ports:
      - 8074:6379
    volumes:
      - redis-data:/data
    networks:
      - sql_server_basket.networks
  
  mongodb_server:
    image: mongo
    container_name: mongodb_server.container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 8072:27017
    volumes:
      - mongodb-data:/data/db
  
  azurite:
    container_name: azurite
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - 8073:10000
    restart: always
    volumes:
      - /home/khauvannam/Azurite/blob-data:/data

networks:
  sql_server_identity.networks:
  sql_server_basket.networks:
