volumes:
  mssql-data:
    driver: local
  redis-cache:
    driver: local

services:
  
  basket_api:
    container_name: basket_api.container
    image: basket_api
    build:
      context: .
      dockerfile: Basket_API/Dockerfile
    depends_on:
      - redis-cache_server
      - sql_server
    ports:
      - 8080:8080
    networks:
      - backend
      - cache_server
  
  identity_api:
    container_name: identity_api.container
    image: identity_api
    build:
      context: .
      dockerfile: Identity_API/Dockerfile
    depends_on:
      - sql_server
    ports:
      - 8081:8080
    networks:
      - backend
  
  product_api:
    container_name: product_api.container
    image: product_api
    build:
      context: .
      dockerfile: Product_API/Dockerfile
    depends_on:
      - sql_server
      - azurite
    ports:
      - 8082:8080
    networks:
      - backend
      - azurite_server
  
  sql_server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server.container
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Nam09189921
    ports:
      - 1433:1433
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - backend
  
  redis-cache_server:
    image: redis
    container_name: redis-cache_server.container
    ports:
      - 8074:6379
    volumes:
      - redis-cache:/data
    networks:
      - cache_server
  
  azurite:
    container_name: azurite
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - 8073:10000
    restart: on-failure
    command: azurite --loose --blobHost 0.0.0.0 --location /data --debug /logs
    volumes:
      - /home/khauvannam/Azurite/blob-data:/data
      - /home/khauvannam/Azurite/logs/debug.log:/logs
    networks:
      - azurite_server

networks:
  cache_server:
  message_broker:
  frontend:
  backend:
  azurite_server:
