# This is a generated file. Not intended for manual editing.
services:
  gateway_api:
    build:
      context: "D:\\Microservice Project\\PetEcommerce"
      dockerfile: "Gateway_API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Gateway_API.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "gateway_api:dev"
    ports: []
    volumes:
    - "C:\\Users\\ADMIN\\.nuget\\packages:/root/.nuget/packages"
    - "D:\\Microservice Project\\PetEcommerce\\Gateway_API:/app:rw"
    - "D:\\Microservice Project\\PetEcommerce:/src:rw"
    working_dir: "/app"
  identity_api:
    build:
      context: "D:\\Microservice Project\\PetEcommerce"
      dockerfile: "Identity_API/Dockerfile"
      target: "bas"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Identity_API.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "identity_api:dev"
    ports: []
    volumes:
    - "C:\\Users\\ADMIN\\.nuget\\packages:/root/.nuget/packages"
    - "D:\\Microservice Project\\PetEcommerce\\Identity_API:/app:rw"
    - "D:\\Microservice Project\\PetEcommerce:/src:rw"
    working_dir: "/app"
  product_api:
    build:
      context: "D:\\Microservice Project\\PetEcommerce"
      dockerfile: "Product_API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Product_API.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "product_api:dev"
    ports: []
    volumes:
    - "C:\\Users\\ADMIN\\.nuget\\packages:/home/app/.nuget/packages"
    - "D:\\Microservice Project\\PetEcommerce\\Product_API:/app:rw"
    - "D:\\Microservice Project\\PetEcommerce:/src:rw"
    working_dir: "/app"
