# This is a generated file. Not intended for manual editing.
services:
  basket_api:
    build:
      context: "/mnt/data1/dotnet-repository/petecommercial-project"
      dockerfile: "Basket_API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Basket_API.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "basket_api:dev"
    ports: []
    volumes:
    - "/home/khauvannam/.nuget/packages:/root/.nuget/packages"
    - "/mnt/data1/dotnet-repository/petecommercial-project/Basket_API:/app:rw"
    - "/mnt/data1/dotnet-repository/petecommercial-project:/src:rw"
    working_dir: "/app"
  identity_api:
    build:
      context: "/mnt/data1/dotnet-repository/petecommercial-project"
      dockerfile: "Identity_API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Identity_API.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "identity_api:dev"
    ports: []
    volumes:
    - "/home/khauvannam/.nuget/packages:/root/.nuget/packages"
    - "/mnt/data1/dotnet-repository/petecommercial-project/Identity_API:/app:rw"
    - "/mnt/data1/dotnet-repository/petecommercial-project:/src:rw"
    working_dir: "/app"
  product_api:
    build:
      context: "/mnt/data1/dotnet-repository/petecommercial-project"
      dockerfile: "Product_API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Product_API.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "product_api:dev"
    ports: []
    volumes:
    - "/home/khauvannam/.nuget/packages:/root/.nuget/packages"
    - "/mnt/data1/dotnet-repository/petecommercial-project/Product_API:/app:rw"
    - "/mnt/data1/dotnet-repository/petecommercial-project:/src:rw"
    working_dir: "/app"
